calibration:
  epochs: 1000
  patience: 50
  cal_lr: 0.01
  cal_weight_decay: 0

  calibrator_name: HETS
  hidden_dim: 32

gnn:
  type: gcn
  num_layer: 2
  hid_dim: 16
  dropout: 0.5
  norm: ~

train:
  epochs: 200
  lr: 0.01
  weight_decay: 0.0005
  patience: ~
